import Head from "next/head";
import { useRouter } from "next/router";
import { FormattedMessage, useIntl } from "react-intl";



export default function Gallery(props) {

const router = useRouter();


  return (
    <div className="">
      <Head>
        <title>Rönnholms blommor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <h1 className="text-4xl font-heading font-medium">Bildgalleri</h1>
        <div className="mx-4 flex flex-col gap-2 md:flex-row">
            <div className="bg-[url(/vaxthus.jpg)] bg-cover relative cursor-pointer" onClick={() => router.push('/galleri/vaxthus')}>
                <div className="flex flex-col justify-center items-center bg-black bg-opacity-40 w-full py-8 md:py-8 md:px-12">
                    <h3 className="text-white text-3xl font-heading">Vårt växthus</h3>
                    <p className="text-neutral-300 pt-4">Klicka för att se mer</p>
                </div>
            </div>
            <div className="bg-[url(/narpes-stad.jpg)] bg-cover bg-center relative cursor-pointer" onClick={() => router.push('/galleri/narpes-stad')}>
                <div className="flex flex-col justify-center items-center bg-black bg-opacity-40 w-full py-8 md:py-8 md:px-12">
                    <h3 className="text-white text-3xl font-heading">Närpes Stad</h3>
                    <p className="text-neutral-300 pt-4">Klicka för att se mer</p>
                </div>
            </div>
            <div className="bg-[url(/mosedal.jpg)] bg-cover relative bg-center cursor-pointer" onClick={() => router.push('/galleri/mosedal')}>
                <div className="flex flex-col justify-center items-center bg-black bg-opacity-40 w-full py-8 md:py-8 md:px-12">
                    <h3 className="text-white text-3xl font-heading">Mosedal</h3>
                    <p className="text-neutral-300 pt-4">Klicka för att se mer</p>
                </div>
            </div>
        </div>

      </main>
    </div>
  );
}


export const getStaticProps = async () => {
  const data = await fetch(
    "https://arzcqb3s2d.execute-api.eu-west-2.amazonaws.com/prod/get-gallery?gallery=vaxthus"
  ).then((response) => response.json());
  return {
    props: { data }
  };
};