import Head from "next/head";
import { useRouter } from "next/router";
import { FormattedMessage, useIntl } from "react-intl";
import FlowersContainer from "../components/FlowersContainer";
import { NavStateContext } from "../context/AppContext";
import { useContext, useEffect, useState } from "react";
import rod2 from "../public/rod-blomma2.jpg";
import Image from "next/image";

export default function Blommor() {
  const { isNavOpen } = useContext(NavStateContext);
  const [flowers, setFlowers] = useState([]);

  const { locales } = useRouter();

  const intl = useIntl();




  return (
    <div className="">
      <Head>
        <title>Rönnholms blommor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="pt-[59px] bg-neutral-100">


        <div className="w-full h-[200px] relative">
          <Image
            src={rod2}
            fill
            placeholder="blur"
            priority
            className="object-cover overflow-hidden"
          />
          <div className="absolute flex flex-col justify-center items-center bg-black bg-opacity-40 w-full px-10 py-8 md:py-8 md:px-12 h-[200px] md:h-[200px]">
            <h1 className="text-white text-3xl font-heading text-center leading-normal">
              Alla blommor
            </h1>
          </div>
        </div>

        <div className="flex justify-center">

        <div className="bg-yellow-100 border-b-2 border-dashed border-neutral-600 md:mt-10 md:w-[50vw] md:text-center md:border-2 md:p-8">
          <h3 className="p-4 text-5xl font-heading leading-normal text-neutral-900">
            Tips!
          </h3>
          <p className="px-4 pb-8 text-xl font-bread leading-normal text-neutral-600">Klicka på hjärtat så sparas blommorna i din lista. <br/> Visa upp listan när du besöker oss så får du snabb hjälp!</p>
        </div>
        </div>
        <FlowersContainer />
      </main>
    </div>
  );
}

