import Head from "next/head";
import { useRouter } from "next/router";
import { FormattedMessage, useIntl } from "react-intl";
import FlowersContainer from "../components/FlowersContainer";
import { NavStateContext } from "../context/AppContext";
import { useContext, useEffect } from "react";

export default function Blommor(props) {
  const { isNavOpen } = useContext(NavStateContext);

  const { locales } = useRouter();

  const intl = useIntl();

  return (
    <div className="">
      <Head>
        <title>Rönnholms blommor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="pt-[59px] bg-neutral-100">
        <div className="bg-[url(/rod-blomma.jpg)] bg-cover bg-bottom md:bg-center relative cursor-pointer h-[200px] md:h-[200px]">
          <div className="flex flex-col justify-center items-center bg-black bg-opacity-40 w-full px-10 py-8 md:py-8 md:px-12 h-[200px] md:h-[200px]">
            <h1 className="text-white text-3xl font-heading text-center leading-normal">
              Alla blommor
            </h1>
          </div>
        </div>
        <div className="flex justify-center">

        <div className="bg-yellow-100 border-b-4 border-dashed border-neutral-600 md:mt-10 md:w-[50vw] md:text-center md:border-2 md:p-8">
          <h3 className="p-4 text-5xl font-heading leading-normal text-neutral-900">
            Tips!
          </h3>
          <p className="px-4 pb-8 text-xl font-bread leading-normal text-neutral-600">Klicka på hjärtat så sparas blommorna i din lista. <br/> Visa upp listan när du besöker oss så får du snabb hjälp!</p>
        </div>
        </div>
        <FlowersContainer data={props.data} />
      </main>
    </div>
  );
}

export const getStaticProps = async () => {
  const data = await fetch(
    "https://arzcqb3s2d.execute-api.eu-west-2.amazonaws.com/prod/get-flowers?type=initial&last=none"
  ).then((response) => response.json());
  return {
    props: { data },
  };
};
