import Head from "next/head";
import useSWR from "swr";
import { useState } from "react";
import Image from "next/image"
import FlowerCard from "../components/FlowerCard";

export default function Home() {
  const [flowers, setFlowers] = useState(null);

  const fetcher = (url) => fetch(url).then((res) => res.json());
  const url =
    "https://arzcqb3s2d.execute-api.eu-west-2.amazonaws.com/prod/get-flowers";

  const { data, error } = useSWR(url, fetcher);

  const newFlowers = () => {
    if (data && !flowers) {
      const sliced = data.slice(0, 10);
      setFlowers(sliced);
      console.log(
        `https://ronnholms-blommor-bilder.s3.eu-west-2.amazonaws.com/${data[0].imgName}`
      );
    }
    return;
  };

  newFlowers();

  return (
    <div className="">
      <Head>
        <title>Rönnholms blommor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="grid grid-cols-1 gap-12 md:grid-cols-2 lg:grid-cols-4 md:gap-x-2 md:gap-y-12 bg-neutral-50">
          {data
            ? data.map((flower, index) => (
                <div className="h-[400px] md:h-[350px] flex flex-col mx-4 shadow-md rounded-3xl" onClick={() => setFlowers("lala")}>
                  <div className="w-full h-4/5 relative">
                    <Image
                      src={`https://ronnholms-blommor-bilder.s3.eu-west-2.amazonaws.com/${flower.imgName}`}
                      alt="lala"
                      fill
                      priority
                      className="object-cover rounded-t-3xl"
                    />
                  </div>
                  <div className="bg-white flex-1 flex items-center justify-center rounded-b-3xl">
                    FlowerName
                  </div>
                </div>
              ))
            : null}
        </div>
      </main>
    </div>
  );
}
