import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { FormattedMessage, useIntl } from "react-intl";
import useSWR from "swr";
import { useState } from "react";
import Image from "next/image"
import FlowerCard from "../components/FlowerCard";
import FlowersContainer from "../components/FlowersContainer";

export default function Home(props) {

  const { locales } = useRouter();

  const intl = useIntl();

  return (
    <div className="">
      <Head>
        <title>Rönnholms blommor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <p>
        <FormattedMessage id="page.home.description" />
        </p>
        <FlowersContainer data={props.data}/>
      </main>
    </div>
  );
}


export const getStaticProps = async () => {
  const data = await fetch(
    "https://arzcqb3s2d.execute-api.eu-west-2.amazonaws.com/prod/get-flowers?type=initial&last=none"
  ).then((response) => response.json());
  return {
    props: { data }
  };
};