import Head from "next/head";
import { useRouter } from "next/router";
import { FormattedMessage, useIntl } from "react-intl";
import FlowersContainer from "../components/FlowersContainer";
import { NavStateContext } from "../context/AppContext";
import { useContext, useEffect } from "react";

export default function Home(props) {

  const { isNavOpen } = useContext(NavStateContext);

  const { locales } = useRouter();

  const intl = useIntl();

  useEffect(() => {
    isNavOpen ? document.body.style.overflow = "hidden" : document.body.style.overflow = "auto";
    isNavOpen ? document.body.style.position = "fixed" : document.body.style.position = "static";
    isNavOpen ? document.body.style.width = "100%" : null;
  })

  return (
    <div className="">
      <Head>
        <title>Rönnholms blommor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <p>
        <FormattedMessage id="page.home.description" />
        </p>
        <FlowersContainer data={props.data}/>
      </main>
    </div>
  );
}


export const getStaticProps = async () => {
  const data = await fetch(
    "https://arzcqb3s2d.execute-api.eu-west-2.amazonaws.com/prod/get-flowers?type=initial&last=none"
  ).then((response) => response.json());
  return {
    props: { data }
  };
};