import Head from "next/head";
import Image from "next/image";
import React, { useState } from "react";
import Link from "next/link";
import { FormattedMessage, useIntl } from "react-intl";
import Contact from "../components/Contact";
import profilePic from "../public/leif.webp";

export default function Kontakt() {
  const intl = useIntl();

  return (
    <div className="">
      <Head>
        <title>Rönnholms blommor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="pt-[59px] pb-36 bg-neutral-100">
        <div className="bg-[url(/kontakt2.jpg)] bg-cover bg-center relative h-[200px] md:h-[200px]">
          <div className="flex flex-col justify-center items-center bg-black bg-opacity-40 w-full px-10 py-8 md:py-8 md:px-12 h-[200px] md:h-[200px]">
            <h1 className="text-white text-3xl font-heading text-center leading-normal">
              Kontakta oss
            </h1>
          </div>
        </div>
        <div className="p-4 pt-16 md:p-40 md:pb-20">
          <div className="flex flex-col md:flex-row items-center gap-8">
            <Image src={profilePic} width={`40vw`} className="rounded-full" />
            <div className="md:pl-12">
              <p className="text-2xl text-neutral-700 text-center md:text-start">
                Nu när du surfat runt på vår hemsida så kanske det finns några frågor som du vill ställa oss. Du kan enkelt skicka ett mail med hjälp av formuläret nedan.
              </p>
              

            </div>
          </div>
          <div className="flex flex-col items-center justify-center pt-8 md:pt-16">

          <Contact/>
          <p className="text-lg text-neutral-600 mt-8 text-center">Om du föredrar att ringa så når du Leif på mobilnummer: +358 50 086 3834</p>
          </div>
        </div>

      </main>
    </div>
  );
}
