import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Link from "next/link";
import { FormattedMessage, useIntl } from "react-intl";
import profilePic from "../public/leif.webp";
import om2 from "../public/om2.jpg";

export default function Om() {
  const intl = useIntl();

  return (
    <div className="">
      <Head>
        <title>Rönnholms blommor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="pt-[59px] pb-36 bg-neutral-100">
        {/* <div className="bg-[url(/om2.jpg)] bg-cover bg-center relative h-[200px] md:h-[200px]">
          <div className="flex flex-col justify-center items-center bg-black bg-opacity-40 w-full px-10 py-8 md:py-8 md:px-12 h-[200px] md:h-[200px]">
            <h1 className="text-white text-3xl font-heading text-center leading-normal">
              Om oss
            </h1>
          </div>
        </div> */}

        <div className="w-[100vw] h-[200px] relative">
          <Image
            src={om2}
            fill
            placeholder="blur"
            priority
            sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              33vw"
            className="object-cover overflow-hidden"
          />
          <div className="absolute flex flex-col justify-center items-center bg-black bg-opacity-40 w-full px-10 py-8 md:py-8 md:px-12 h-[200px] md:h-[200px]">
            <h1 className="text-white text-3xl font-heading text-center leading-normal">
              Om oss
            </h1>
          </div>
        </div>
        <div className="p-4 pt-16 md:p-40 md:pb-20">
          <div className="flex flex-col md:flex-row items-center gap-8">
            <Image src={profilePic} width={`40vw`} className="rounded-full" />
            <div className="md:pl-12">
              <p className="text-xl md:text-2xl italic text-neutral-700">
                År 2013 startade vi (Leif och Inger) verksamheten i liten skala
                och sedan dess har den bara växt sig större och större. Nu gläds
                vi åt att varje år få ta hjälp utav duktiga säsongsarbetare och
                att få träffa trevliga kunder från alla olika håll.
              </p>

              <p className="text-xl md:text-2xl font-bread italic pt-8 text-neutral-700">
                Vårt utbud av blommor består av livliga färger och rik
                variation, allt från de vanligaste vår- och sommarblommorna till
                Cannor, Hortensia amplar och Alstromerior. Dessutom prövar vi
                varje år på nya sorter och färger för att göra din
                blomsterhandling ännu mer intresssant! Vi köper största delen av
                våra blommor som små sticklingar av inhemska leverantörer.
              </p>
            </div>
          </div>
          <p className="text-xl md:text-2xl font-bread italic pt-8 text-neutral-700 pb-8">
            Vi säljer även tillbehör som torv och mylla samt utekrukor (bilder
            kommer senare). Ta gärna kontakt med oss eller kom förbi vårt
            växthus i Övermark så får du ta del av goda råd och förslag på vad
            som passar till olika planteringar men även planteringshjälp! Vi har
            även försäljning under högsäsongen maj-juli i ett litet växthus på
            Tegelbruksvägen 1 i Närpes. Vår säsong börjar i februari och
            sträcker sig till slutet av sommaren.
          </p>
          <div className="flex justify-center pt-8">
            <Link href="/kontakt">
              <button className="py-6 px-12 bg-rose-500 rounded-3xl text-2xl text-neutral-200 shadow-xl hover:bg-rose-600">
                Kontakta oss
              </button>
            </Link>
          </div>
        </div>
      </main>
    </div>
  );
}
