import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { FormattedMessage, useIntl } from "react-intl";
import oppet2 from "../public/solros2.jpg";

export default function Om() {
  const intl = useIntl();

  return (
    <div className="">
      <Head>
        <title>Rönnholms blommor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="pt-[59px] pb-60 bg-neutral-100">


        <div className="w-full h-[200px] relative">
          <Image
            src={oppet2}
            fill
            placeholder="blur"
            priority
            className="object-cover overflow-hidden"
          />
          <div className="absolute flex flex-col justify-center items-center bg-black bg-opacity-40 w-full px-10 py-8 md:py-8 md:px-12 h-[200px] md:h-[200px]">
            <h1 className="text-white text-3xl font-heading text-center leading-normal">
              Öppettider
            </h1>
          </div>
        </div>

        <div className="p-4 pt-16 md:p-40">
            <div className="bg-yellow-100 text-center text-2xl py-20 border-2 border-dashed border-neutral-400">
                <p>Information kring försäljningsplatser och öppettider kommer snart!</p>
            </div>
        </div>
      </main>
    </div>
  );
}
